//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by 081226_camera_param_PF.rc
//
#define IDD_MY081226_CAMERA_PARAM_PF_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDC_CHECK_CAPTURE_IMG_IS_EXPOSURE 1000
#define IDC_CHECK_CAPTURE_IMG_IS_FOCUS  1001
#define IDC_STATIC_CAPTURE_IMG_TIME     1002
#define IDC_BUTTON_CAPTURE_IMG          1003
#define IDC_COMBO_IMG_SET               1004
#define IDC_STATIC_MEASURE_ENTROPY_SCAN_ALL_IMG 1005
#define IDC_STATIC_MEASURE_ENTROPY_SCAN_ALL_ENTROPY 1006
#define IDC_BUTTON_MEASURE_ENTROPY_SCAN_ALL 1007
#define IDC_EDIT_MEASURE_ENTROPY_LOCAL_MAXIMA_WIN_HEIGHT 1008
#define IDC_EDIT_MEASURE_ENTROPY_LOCAL_MAXIMA_WIN_WIDTH 1009
#define IDC_BUTTON_MEASURE_ENTROPY_LOCAL_MAXIMA 1010
#define IDC_STATIC_PF_IMG               1011
#define IDC_STATIC_ENERGY_LP_RESULT_IMG 1012
#define IDC_STATIC_MEASURE_ENTROPY_TIME 1013
#define IDC_BUTTON_QUIT                 1014
#define IDC_EDIT_MEASURE_ENTROPY_LOCAL_MAXIMA_CENTER_EXP 1015
#define IDC_EDIT_MEASURE_ENTROPY_LOCAL_MAXIMA_CENTER_FOCUS 1016
#define IDC_BUTTON_PF_RUN               1017
#define IDC_STATIC_PF_TIME              1018
#define IDC_EDIT_PF_NUM                 1019
#define IDC_EDIT_PF_POSITION_SIGMA      1020
#define IDC_EDIT_PF_VELOCITY_SIGMA      1021
#define IDC_EDIT_PF_INIT_EXP            1022
#define IDC_EDIT_PF_INIT_FOCUS          1023
#define IDC_BUTTON_ENERGY_LP_SCAN_ALL   1024
#define IDC_BUTTON_MEASURE_ENTROPY_LOCAL_MAXIMA2 1025
#define IDC_EDIT_MEASURE_ENTROPY_LOCAL_MAXIMA_RANDOM_NUM 1026
#define IDC_STATIC_ENERGY_LP_RESULT_ENERGY 1027
#define IDC_STATIC_ENERGY_LP_TIME       1028
#define IDC_BUTTON_TOOL_LOAD_IMG        1029
#define IDC_BUTTON_TOOL_EDGE_DETECT     1030
#define IDC_CHECK_IMG_SET_PREVIOUS      1031
#define IDC_BUTTON_TOOL_LINE_DETECT     1032
#define IDC_EDIT_TOOL_LINE_DETECT_THR   1033
#define IDC_STATIC_N_DETECTED_LINES     1034
#define IDC_EDIT_MEASURE_ENERGY_LOCAL_MAXIMA_WIN_HEIGHT 1035
#define IDC_EDIT_MEASURE_ENERGY_LOCAL_MAXIMA_WIN_WIDTH 1036
#define IDC_EDIT_MEASURE_ENERGY_LOCAL_MAXIMA_CENTER_EXP 1037
#define IDC_EDIT_MEASURE_ENERGY_LOCAL_MAXIMA_CENTER_FOCUS 1038
#define IDC_BUTTON_MEASURE_ENERGY_LOCAL_MAXIMA 1039
#define IDC_STATIC_N_DETECTED_LINES2    1040

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1035
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
